version: "3"
services:
  musiq:
    build: .
    networks:
      - nginx-sidecar
    environment:
      PORT: 80
      VIRTUAL_HOST: musiq-dev.strukteon.net
      LETSENCRYPT_HOST: musiq-dev.strukteon.net
      LETSENCRYPT_EMAIL: sensentod@gmail.com

networks:
  nginx-sidecar:
    external:
      name: letsencrypt